name: numeroid
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  go_router: ^14.2.1
  dio: ^5.5.0
  get_it: ^7.7.0
  injectable: ^2.4.2
  easy_localization: ^3.0.7
  json_annotation: ^4.9.0
  flutter_bloc: ^8.1.6
  url_launcher: ^6.3.0
  flutter_secure_storage: ^9.2.2
  cached_network_image: ^3.3.1
  freezed_annotation: ^2.4.1
  maplibre_gl: ^0.20.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.11
  injectable_generator: ^2.6.1
  json_serializable: ^6.8.0
  freezed: ^2.5.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/promo/
    - assets/icons/
    - assets/icons/facilities/
    - assets/lang/
    - assets/jsons/
    - assets/texts/

  fonts:
    - family: Rawline
      fonts:
        - asset: assets/fonts/rawline-400-regular.ttf
          weight: 400
        - asset: assets/fonts/rawline-500-medium.ttf
          weight: 500
        - asset: assets/fonts/rawline-600-semibold.ttf
          weight: 700
        - asset: assets/fonts/rawline-700-bold.ttf
          weight: 700
