name: numeroid
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  auto_route: ^8.0.3
  dio: ^5.4.3+1
  get_it: ^7.6.9
  injectable: ^2.4.1
  easy_localization: ^3.0.5
  json_annotation: ^4.8.1
  flutter_bloc: ^8.1.5
  url_launcher: ^6.2.6
  flutter_secure_storage: ^9.0.0
  maplibre_gl:
    git:
      url: https://github.com/maplibre/flutter-maplibre-gl.git
      ref: main

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  auto_route_generator: ^8.0.0
  build_runner: ^2.4.9
  injectable_generator: ^2.6.1
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/promo/
    - assets/icons/
    - assets/lang/
    - assets/jsons/
    - assets/texts/

  fonts:
    - family: Rawline
      fonts:
        - asset: assets/fonts/rawline-400-regular.ttf
          weight: 400
        - asset: assets/fonts/rawline-500-medium.ttf
          weight: 500
        - asset: assets/fonts/rawline-600-semibold.ttf
          weight: 700
        - asset: assets/fonts/rawline-700-bold.ttf
          weight: 700
