name: Flutter Build

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build-android:
    name: Build Android APK
    runs-on: mac-runner # Ваш self-hosted runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.0'

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk

      - name: Upload APK as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: android-apk
          path: build/app/outputs/flutter-apk/app-release.apk

  build-ios:
    name: Build iOS IPA
    runs-on: mac-runner # Ваш self-hosted runner
    needs: build-android

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.0'

      - name: Install dependencies
        run: flutter pub get

      - name: Build IPA
        run: flutter build ipa --export-options-plist=sign/ios/exportOptionsBeta.plist

      - name: Upload IPA as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ios-ipa
          path: build/ios/ipa/*.ipa