name: Flutter Build

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  common:
    name: Common Setup
    runs-on: flutter-runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: flutter pub get

      - name: Set execute permissions for build_common.sh
        run: chmod +x ci/scripts/build_common.sh

      - name: Run common build script
        run: |
          BUILD_NUMBER=${{ github.run_number }}
          REPO_NAME=$(basename $GITHUB_REPOSITORY)
          ci/scripts/build_common.sh -b $BUILD_NUMBER -n $REPO_NAME

      - name: Save generated files as artifact
        uses: actions/upload-artifact@v4
        with:
          name: common-artifact-lib
          path: lib/
          retention-days: 1

  build-android:
    name: Build Android APK
    runs-on: flutter-runner
    needs: common

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set execute permissions for build_android.sh
        run: chmod +x ci/scripts/build_android.sh

      - name: Download generated files
        uses: actions/download-artifact@v4
        with:
          name: common-artifact-lib
          path: ./lib/

      - name: Build Android APK
        id: build_apk
        run: |
          REPO_NAME=$(basename $GITHUB_REPOSITORY)
          VERSION_NAME=$(grep '^version: ' pubspec.yaml | cut -d ' ' -f 2)
          APK_NAME="${REPO_NAME}-${VERSION_NAME}-beta.apk"
          ci/scripts/build_android.sh -n $REPO_NAME -v $VERSION_NAME
          echo "apk_name=${APK_NAME}" >> $GITHUB_ENV

      - name: Upload APK as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.build_apk.outputs.apk_name }}
          path: build/artifacts/android/${{ steps.build_apk.outputs.apk_name }}

  build-ios:
    name: Build iOS IPA
    runs-on: flutter-runner
    needs: common

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set execute permissions for build_ios.sh
        run: chmod +x ci/scripts/build_ios.sh

      - name: Download generated files
        uses: actions/download-artifact@v4
        with:
          name: common-artifact-lib
          path: ./lib/

      - name: Build iOS IPA
        id: build_ipa
        run: |
          REPO_NAME=$(basename $GITHUB_REPOSITORY)
          VERSION_NAME=$(grep '^version: ' pubspec.yaml | cut -d ' ' -f 2)
          IPA_NAME="${REPO_NAME}-${VERSION_NAME}-beta.ipa"
          ci/scripts/build_ios.sh -n $REPO_NAME -v $VERSION_NAME
          echo "ipa_name=${IPA_NAME}" >> $GITHUB_ENV

      - name: Upload IPA as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.build_ipa.outputs.ipa_name }}
          path: build/artifacts/ios/${{ steps.build_ipa.outputs.ipa_name }}