name: Flutter Build

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  common:
    name: Common Setup
    runs-on: flutter-runner

    env:
      ENV_VERSION: ${{ github.ref == 'refs/heads/main' && 'prod' || 'dev' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: flutter pub get

      - name: Set execute permissions for scripts
        run: chmod +x ci/scripts/*.sh

      - name: Run common build script
        run: |
          BUILD_NUMBER=${{ github.run_number }}
          NAME=$(basename $GITHUB_REPOSITORY)
          ci/scripts/build_common.sh -b $BUILD_NUMBER -n $NAME

      - name: Save generated files as artifact
        uses: actions/upload-artifact@v4
        with:
          name: common-artifacts
          path: |
            lib/
            pubspec.yaml
          retention-days: 1

  build-android:
    name: Build Android APK
    runs-on: flutter-runner
    needs: common

    env:
      ENV_VERSION: ${{ github.ref == 'refs/heads/main' && 'prod' || 'dev' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set execute permissions for build_android.sh
        run: chmod +x ci/scripts/build_android.sh

      - name: Set execute permissions for gen_filename.sh
        run: chmod +x ci/scripts/gen_filename.sh

      - name: Download generated files
        uses: actions/download-artifact@v4
        with:
          name: common-artifacts
          path: ./

      # This step might trigger a linter warning, but it's intentional
      - name: Build Android APK
        run: |
          NAME=$(basename $GITHUB_REPOSITORY)
          FILENAME=$(ci/scripts/gen_filename.sh -n $NAME -p android -e ${{ env.ENV_VERSION }})
          ci/scripts/build_android.sh -n $NAME -e ${{ env.ENV_VERSION }}
          echo "APK_NAME=${FILENAME}.apk" >> $GITHUB_ENV
      
      # This line might trigger a linter warning, but it's intentional
      - name: Upload APK as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.APK_NAME }}
          path: build/artifacts/android/${{ env.APK_NAME }}

  build-ios:
    name: Build iOS IPA
    runs-on: flutter-runner
    needs: common

    env:
      ENV_VERSION: ${{ github.ref == 'refs/heads/main' && 'prod' || 'dev' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set execute permissions for build_ios.sh
        run: chmod +x ci/scripts/build_ios.sh

      - name: Set execute permissions for gen_filename.sh
        run: chmod +x ci/scripts/gen_filename.sh

      - name: Download generated files
        uses: actions/download-artifact@v4
        with:
          name: common-artifacts
          path: ./

      # This step might trigger a linter warning, but it's intentional
      - name: Build iOS IPA
        run: |
          NAME=$(basename $GITHUB_REPOSITORY)
          FILENAME=$(ci/scripts/gen_filename.sh -n $NAME -p ios -e ${{ env.ENV_VERSION }})
          ci/scripts/build_ios.sh -n $NAME -e ${{ env.ENV_VERSION }}
          echo "IPA_NAME=${FILENAME}.ipa" >> $GITHUB_ENV

      # This step might trigger a linter warning, but it's intentional
      - name: Upload IPA as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.IPA_NAME }}
          path: build/artifacts/ios/${{ env.IPA_NAME }}