name: Flutter Build

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  common:
    name: Common Setup
    runs-on: flutter-runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: flutter pub get

      - name: Set execute permissions for build_common.sh
        run: chmod +x ci/scripts/build_common.sh

      - name: Run common build script
        run: |
          BUILD_NUMBER=${{ github.run_number }}
          REPO_NAME=$(basename $GITHUB_REPOSITORY)
          ci/scripts/build_common.sh -b $BUILD_NUMBER -n $REPO_NAME

          # Извлечение версии с номером сборки из pubspec.yaml и сохранение в переменной окружения
          VERSION_NAME=$(grep '^version: ' pubspec.yaml | cut -d ' ' -f 2)
          echo "VERSION_NAME=${VERSION_NAME}" >> $GITHUB_ENV

      - name: Save generated files as artifact
        uses: actions/upload-artifact@v4
        with:
          name: common-artifacts
          path: |
            lib/
            pubspec.yaml
          retention-days: 1

  build-android:
    name: Build Android APK
    runs-on: flutter-runner
    needs: common

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set execute permissions for build_android.sh
        run: chmod +x ci/scripts/build_android.sh

      - name: Download generated files
        uses: actions/download-artifact@v4
        with:
          name: common-artifacts
          path: ./

      - name: Build Android APK
        run: |
          REPO_NAME=$(basename $GITHUB_REPOSITORY)
          ci/scripts/build_android.sh -n $REPO_NAME
          # Извлечение версии из pubspec.yaml
          VERSION_NAME=$(grep '^version: ' pubspec.yaml | cut -d ' ' -f 2)
          APK_NAME="${REPO_NAME}-android-${VERSION_NAME}-beta.apk"
          echo "APK_NAME=${APK_NAME}" >> $GITHUB_ENV

      - name: Upload APK as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.APK_NAME }}
          path: build/artifacts/android/${{ env.APK_NAME }}

  build-ios:
    name: Build iOS IPA
    runs-on: flutter-runner
    needs: common

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set execute permissions for build_ios.sh
        run: chmod +x ci/scripts/build_ios.sh

      - name: Download generated files
        uses: actions/download-artifact@v4
        with:
          name: common-artifacts
          path: ./

      - name: Build iOS IPA
        run: |
          REPO_NAME=$(basename $GITHUB_REPOSITORY)
          IPA_NAME="${REPO_NAME}-ios-${VERSION_NAME}-beta.ipa"
          ci/scripts/build_ios.sh -n $REPO_NAME
          echo "IPA_NAME=${IPA_NAME}" >> $GITHUB_ENV

      - name: Upload IPA as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.IPA_NAME }}
          path: build/artifacts/ios/${{ env.IPA_NAME }}